### PR TITLE
Improvements and utils methods

### PR DESCRIPTION
**Pull request by MessuKilkain**

### CODE REVIEW

**Comment by DZamataev** [comment]
Hi @MessuKilkain! Great pull request! I will review it soon. Thank you for your attention!

**Comment by DZamataev** [comment]
I've pushed version 0.4.0 with your PR. Thank you!

**Comment by MessuKilkain** [comment]
Thanks to you for the player. It saved me a lot of time on dev... and now I can celebrate my first pull request done. Hooray! ^^

**Comment by DZamataev** [comment]
Congratulations! Wish you a happy time sharing your code!

**Pull request merged**
